# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SatisStokHareketleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.Satis')),
            ],
        ),
        migrations.CreateModel(
            name='uretici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uretici_adi', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=500)),
                ('banka_bilgileri', models.CharField(max_length=500)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200)),
                ('uye_fiyati', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('musteri_fiyati', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('birim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.Birim')),
                ('uretici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.uretici')),
            ],
        ),
        migrations.AddField(
            model_name='satisstokhareketleri',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.urun'),
        ),
    ]
