# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koopmuhasebe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderTipi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gider_adi', models.CharField(max_length=50)),
            ],
        ),
    ]
