# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koopmuhasebe', '0002_gidertipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('notlar', models.CharField(max_length=500)),
                ('gider_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.GiderTipi')),
            ],
        ),
    ]
