# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koopmuhasebe', '0003_gider'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokGirisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('miktar', models.IntegerField()),
                ('notlar', models.CharField(max_length=500)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koopmuhasebe.urun')),
            ],
        ),
    ]
