# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koopmuhasebe', '0004_stokgirisi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uretici',
            options={'permissions': (('can_view_uretici', 'Can View Uretici'),)},
        ),
    ]
