# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('koopmuhasebe', '0006_auto_20170506_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirmanVeDuzeltme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notlar', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VirmanVeDuzeltmeHesaplari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='virmanveduzeltme',
            name='cikis_hesabi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cikis_hesabi', to='koopmuhasebe.VirmanVeDuzeltmeHesaplari'),
        ),
        migrations.AddField(
            model_name='virmanveduzeltme',
            name='giris_hesabi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giris_hesabi', to='koopmuhasebe.VirmanVeDuzeltmeHesaplari'),
        ),
        migrations.AddField(
            model_name='virmanveduzeltme',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
